### ISSUE TITLE
JVM Crash | Краш виртуальной машины

### ISSUE THREAD

**Issue by GiaNTizmO** [xWhitey/JavaDumper#1]
Привет. Крашится JVM при разных ситуациях, сейчас опишу:
1) Если заинжектить дампер в меню игры и просто зайти в одиночку
[hs_err_pid10668.log](https://github.com/xWhitey/JavaDumper/files/6950566/hs_err_pid10668.log)
[tl-logger3448135206580660720.txt](https://github.com/xWhitey/JavaDumper/files/6950567/tl-logger3448135206580660720.txt)
2) Для теста взял чит: https://github.com/GishReloaded/Gish-Code-1.12.2 и как я понял - чтоб сдампить классы, мне надо инжектить сначала дампер, а потом уже чит. Если так делаю - получаю краш при инжекте GishReloaded:
[hs_err_pid6012.log](https://github.com/xWhitey/JavaDumper/files/6950569/hs_err_pid6012.log)
[tl-logger600647548072730369.txt](https://github.com/xWhitey/JavaDumper/files/6950570/tl-logger600647548072730369.txt)
(Пробовал с AGENT и TEST MODE, не помогло)

Версия Java:
_java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)_

Правда либу jvm.lib я взял с AdoptOpenJDK1.8, но думаю роли не играет.

**Comment by xWhitey** [comment]
Привет. Читы которые сделанв в jar-to-dll таким образом сдампить нельзя, могу рассказать в дискорде как сдампить такие читы (port#5207),  так же попробуй скомпилировать в Debug x64, если выбран Release x64 и наоборот
